version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
    - "8080:8080"
    restart: always
    links:
      - redis
      - cassandra
    depends_on:
      - redis
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data
    restart: always
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    container_name: cassandra
    ports:
      - "9142:9042"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra